title: Farishah N.
logo: "/images/farishah-bitmoji.jpg?raw=true" 
description: > 
  <br><br>
  [About Me](/aboutme)
  <br><br>
  Software Engineer @ Citi 
  <br><br>
  MS in Software Engineering @ UTD 
  <br><br>  
 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
